openapi: 3.0.4
info:
  title: Cryptomarket log models
  description: Log models for logging services of cryptomarket
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        or:
          $ref: '#/components/schemas/CpmkLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    CpmkLogModel:
      title: Модель лога для микросервиса Cryptomarket
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
        requestOr:
          $ref: '#/components/schemas/OrLog'
        requestFilter:
          $ref: '#/components/schemas/OrFilterLog'
        responseOr:
          $ref: '#/components/schemas/OrLog'
        responseOrs:
          type: array
          items:
            $ref: '#/components/schemas/OrLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    OrLog:
      title: Модель лога для заявки
      type: object
      properties:
        id:
          type: string
        accountNumber:
          type: string
        walletNumber:
          type: string
        fiatCurrency:
          type: string
        cryptoCurrency:
          type: string
        action:
          type: string
        value:
          type: string
        ownerId:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    OrFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
        action:
          type: string

